version: '3.9'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
      - ./script:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - db_mongo_backend

  netflics:
    container_name: netflics_back_end
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./target/classes/application.properties:/src/main/resources
    depends_on:
      - mongodb
    networks:
      - db_mongo_backend
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://user:user@mongodb:27017/netflics
    restart: on-failure

networks:
  db_mongo_backend:
    name: db_mongo_backend
